ユーザ登録できるように修正
shigakijGitHub/rails_work_nj pull request #17
Opened 2020-04-12 13:50 UTC by naotsukamoto

developにmergeプルリクだせた！
※コマンドから直接はできんらしいｗ

2020-04-14 15:57 UTC, shigakijGitHub requested changes
railsとrubyがまだ不勉強だからソースについてはレビューできるほどよくわかんなかった。笑

ただ、コントローラーについてはなるべくコメント残すようにして欲しいです！
これ大事。

なんで、コメントおなしゃす！

2020-04-15 14:50 UTC, naotsukamoto commented
select_controller.rbに追加したインスタンス作成のコメント追加しました！

2020-04-15 14:50 UTC, shigakijGitHub approved these changes
過剰な気もするけど笑、いい感じ！！
マージします！！

2020-04-15 14:50 UTC, merged

2020-04-15 14:51 UTC, naotsukamoto commented
🙏